name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        cache-dependency-path: 'backend/go.sum'

    - name: Install dependencies
      run: go mod download

    - name: Build project
      run: go build -v ./...
      
    - name: Run tests
      run: go test -v ./...